# Generated by Django 2.1.7 on 2019-06-30 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_id', models.IntegerField()),
                ('P_name', models.CharField(max_length=300)),
                ('P_code', models.IntegerField()),
                ('P_price', models.IntegerField()),
                ('P_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('qty', models.FloatField()),
                ('Total', models.FloatField()),
                ('P_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_cat_id', models.IntegerField()),
                ('Sub_cat_name', models.CharField(max_length=300)),
                ('Sub_image', models.ImageField(upload_to='images/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Category')),
            ],
        ),
    ]
