# Generated by Django 2.1.7 on 2019-07-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_image',
            field=models.URLField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='Sub_image',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
