# Generated by Django 2.2.3 on 2019-07-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_paradigm_programmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paradigm',
            old_name='paradigm',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='language',
            name='paradigm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.paradigm'),
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='language',
        ),
        migrations.AddField(
            model_name='programmer',
            name='language',
            field=models.ManyToManyField(to='languages.language'),
        ),
    ]
